### ISSUE TITLE
Add Pleroma, Misskey and Hubzilla

### ISSUE THREAD

**Issue by EchedeyLR** [LinuxCafeFederation/awesome-alternatives#1]
- https://pleroma.social/
- https://github.com/syuilo/misskey
- https://zotum.net/help/en/about/about

**Comment by CipherOps** [comment]
Misskey seems to be an alternative to Tumblr, what about the other two services? I add software to this list that is alternatives to proprietary services.

**Comment by EchedeyLR** [comment]
Sorry for my delay, MissKey is made from scratch itself and federates through ActivityPub well with Pleroma and Mastodon as well as Pixelfed. 

It was announced as a multi-purpose social networking software. I think that Facebook can be compared to it in a good way with games, etc.

**Comment by EchedeyLR** [comment]
Pleroma/Akkoma is not listed.
